name: Build

on: [push, pull_request]

env:
  SCARB_VERSION: 2.3.1

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.3.1"
      - name: Check cairo format
        run: scarb fmt --check
        working-directory: contracts
      - name: Build cairo programs
        run: scarb build
        working-directory: contracts
